### ISSUE TITLE
Create design for and implement multiple directions of one line

### ISSUE THREAD

**Issue by twarowskiw** [jakniedojade/jakniedojade-web-gui#15]
Backend is going to return multiple directions for some lines. We can to display them like <icon?> <line-number> <first-stop> <some-arrow-maybe?> <last-stop>

**Comment by twarowskiw** [comment]
to be done when backend return said data

**Comment by SimonFine** [comment]
I think we decided to stick with two directions for now

**Comment by twarowskiw** [comment]
Closed, we will open a new issue when (if ever) we decide to use multiple directions
