### ISSUE TITLE
Optimizations for production deployments

### ISSUE THREAD

**Issue by pawheb** [jakniedojade/jakniedojade-web-gui#36]
Currently based on Azure static web apps github workflow documentation (https://learn.microsoft.com/en-us/azure/static-web-apps/build-configuration?tabs=adt&pivots=github-actions), their build system "Oryx" defaults to building with the `npm run build` or `npm run build:azure` commands.

![image](https://github.com/user-attachments/assets/a3f6e45b-9ee8-458e-907a-254dd14c54dc)

Can we optimize our app somehow with Angular configuration options? Are we already maybe doing something like this in `angular.json`? If yes then we should specify a custom production build command for Azure, if not then this should be considered.

**Comment by twarowskiw** [comment]
We already have npm run build which simply launches ng build. For now, we don't seem to need anything specific in the static production build, but if anything comes up, the build command will be modified
