### ISSUE TITLE
Bug fixes

### ISSUE THREAD

**Issue by SimonFine** [jakniedojade/jakniedojade-web-gui#8]
- [x] Input text in search component seems to be matching only in lowercase
- [x] We need to add error handling when poles array in linedata is empty (line 409)
- [x] Max zoom out level has to be increased because some routes don't fit
- [x] Set better zoom snapping for route bounds fit (now it rounds to nearest integer zoom level)
- [x] Activearea seems not working at all

**Comment by twarowskiw** [comment]
- [ ] enlarge click area of stops
